# configuration file for workflow.
# this is deisgned to be the user's point of contact with the workflow, any adjustments or inputs are intended to be placed here.
# this should allow users to not have to become familiar with the entire workflow to use it.


# partition parts of ccs to parallelize and run faster
# CORES: number of threads PER chunk of ccs partition. To change the number of cores used by the workflow specify them when submitting the jobscript
# number of threads to use

CHUNKS: 100
CORES: 10

# LOGLEVEL: log level for ccs, values: #TRACE, DEBUG, INFO, WARN, FATAL
# LINEAGE: database to use for BUSCO
# KMER: kmer size for fastk
# INDEX_SPLIT: "split index for every ~NUM input bases" relevant for minimap2. Defuult = 4G
LOGLEVEL: INFO
LINEAGE: cyprinodontiformes_odb10
KMER: 30
INDEX_SPLIT: 200G

# if using HIFI copy it to the working directory
# ENZYMES: specify multiuple enzymes with comma without space -- need the sequence not the name
# FILE_PREFIX: prefix for output names, all non characters will be removed
SUBREADS: /path/to/subreads/identifier.subreads.bam
HIFI: /path/tohifireads/another_identifier.[fq|fastq|fast.gz|fq.gz]
HIC1: /path/to/hicreads/Hic_identifier_R1.fastq.gz
HIC2: /path/to/hicreads/Hic_identifier_R1.fastq.gz
FILE_PREFIX: MySpecies123
ADAPTERS: HiFiAdapterFilt/DB

# path to a locally installed merquryFK initialized with make:
# https://github.com/thegenemyers/MERQURY.FK
# don't include the last backslash
MERQURY_DIR: "/home/user/MERQURY.FK-1.0.0"

FASTK_MODULE: "fastk/current"
GCC_MODULE: "gcc/11.2.0"
GENOMESCOPE_MODULE: "genescopefk/current"
GATK_MODULE: "gatk/4.4.0.0"
SALSA2_MODULE: "salsa2/2.3"


# load module with latest deepconsensus or specify how to run it on your system
# if you have a different version edit the checkpoint file
# if you have installed it another way, edit this string or 
#edit the code directly to load the program effectively
DEEPCONSENSUS_RUN_METHOD: "module load deepconsensus/1.2.0"

# path to deepconsensus version checkpoint model location
DEEPCONSENSUS_MODEL_CHECKPOINT: "model/1.2/checkpoint"

#include final backslash
BUSCO_DATASET_FOLDER: "/path/to/busco_downloads/"

# kraken database of your choice. can be downloaded from:
# https://benlangmead.github.io/aws-indexes/k2
KRAKEN_DB: "/path/to/databases/kraken"

# choose a confidence level you feel comfortable with.
# kraken confidence scores are not obvious to set yet
# start understanding confidence scores here:
# https://github.com/DerrickWood/kraken2/wiki/Manual#confidence-scoring
KRAKEN_CONFIDENCE: 0.51

# path to salsa bin file where one can find the file filter_five_end.pl
SALSA2_BIN_FOLDER: /path/to/salsa2/bin

# Specify which operations to run, accepted values: True, False
DO_CCS: True
DO_DEDUP: True
DO_ADAPT_FILT: True
DO_BUSCO: True
DO_HIC: True
DO_CONTACT_MAP: True
DO_STATS: True

# a convenient way to only run hifiasm. Niche -- might remove or redesign in the future depending on what's added to the pipeline
STOP_AT_HIFIASM: False


